<%@ page contentType="text/html; charset=utf-8" language="java" errorPage="" %>

<!--meta-->
<meta http-equiv="Content-Type" content="text/html;charset=utf-8">
<meta name="viewport"
      content="initial-scale=1,maximum-scale=1,minimum-scale=1, user-scalable=no,width=320, target-densitydpi=device-dpi">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black">
<meta name="format-detection" content="telephone=no">

<!--外部样式-->
<link rel="stylesheet" type="text/css" href="js/m.tool.juxinbox.com/style.css"/>

<!--外部依赖-->
<script src="js/jquery/jquery-2.1.0.min.js"></script>
<script src="js/m.tool.juxinbox.com/main.js?<%=v%>"></script>

<!--微信js-->
<script src="js/jweixin-1.0.0.js"></script>

<!--全局样式-->
<link rel="stylesheet" type="text/css" href="css/common.css?<%=v%>"/>

<!--全局设置-->
<script src="js/config.js?<%=v%>"></script>

<!--全局方法-->
<script src="js/common.js?<%=v%>"></script>

